default: gaga
timelines:
  - key: gaga
    title: A GaGa Mind
    button: Speechless
    page_bg: /img/gaga-background.jpg
    tweetbox_bg: /img/gaga-box.jpg
    tweetbox_min_height: '50px'
    twittername: ladygaga

  - key: justinbieber
    title: '@justinbieber'
    button: '#believe'
    page_bg: /img/bieber-background.jpg
    tweetbox_bg: /img/bieber-box.png
    tweetbox_min_height: '60px'
    twittername: justinbieber
